### ISSUE TITLE
ShapefileException: Shapefile Reader requires a shapefile or file-like object. (no dbf file found)

### ISSUE THREAD

**Issue by franciswguevara** [ljyflores/Address-to-Barangay#1]
Hi! When you run the code as is, you get this error even if the shp file exists. 

After lots of digging I found out that you need the shp file's companion files (.dbf, .shx, .prj, etc.) for the reader to work. And these aren't included in the downloadable file.

Source: https://gis.stackexchange.com/questions/262505/python-cant-read-shapefile

Thank you so much for this! I really appreciate your work. :)

**Comment by ljyflores** [comment]
Hi Francis, I added extra files to the code – I hope this addresses the issue!
